//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTrucThuThu
    {
        public int MaLichTruc { get; set; }
        public int MaNguoiDung { get; set; }
        public System.DateTime NgayTruc { get; set; }
        public System.TimeSpan GioBatDau { get; set; }
        public System.TimeSpan GioKetThuc { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
