//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SachTrongDanhSach
    {
        public int MaSachTrongDanhSach { get; set; }
        public int MaDanhSach { get; set; }
        public int MaSach { get; set; }
        public System.DateTime NgayThem { get; set; }
    
        public virtual DanhSachSachCaNhan DanhSachSachCaNhan { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
